USE TASKONE;

ALTER TABLE STUDENT -- ALTER IS FOR MODIFICATIONS IN THE TABLES
ADD AGE INT NOT NULL;

UPDATE STUDENT
SET AGE = 21
WHERE STUDENT_ID = 1;

UPDATE STUDENT
SET AGE = CASE
	WHEN STUDENT_ID = 2 THEN 22
    WHEN STUDENT_ID = 3 THEN 20
    WHEN STUDENT_ID = 4 THEN 25
    WHEN STUDENT_ID = 5 THEN 21
    WHEN STUDENT_ID = 6 THEN 23
    WHEN STUDENT_ID = 7 THEN 20
    WHEN STUDENT_ID = 8 THEN 21
    WHEN STUDENT_ID = 9 THEN 24
    WHEN STUDENT_ID = 10 THEN 22
    END
    WHERE STUDENT_ID IN (2,3,4,5,6,7,8,9,10);

-- FOR ENTIRE DATA 
SELECT* 
FROM STUDENT;
-- FOR PARTICULAR COLUMN DATA - STUDENT NAMES
SELECT STUDENT_NAME
FROM STUDENT;
-- FOR AGE COLUMN
SELECT AGE 
FROM STUDENT;
-- FOR STUIDENTS EMAIL-ID
SELECT EMAIL_ID
FROM STUDENT;

-- FOR DEPARTMENT TABLE
SELECT*
FROM DEPARTMENT;
-- FOR DEPARTMENT NAMES
SELECT DEPT_NAME
FROM DEPARTMENT;

-- FOR MANUALS TABLE
SELECT* FROM MANUALS;
-- FOR MANUAL NAMES
SELECT MANUAL_NAME
FROM MANUALS;
-- FOR PUBLISH YEAR OR DATE
SELECT PUBLISHED_YEAR
FROM MANUALS;

-- USING WHERE CLAUSE 
SELECT STUDENT_NAME ,AGE 
FROM STUDENT
WHERE AGE > 22;

SELECT MANUAL_NAME, MANUAL_PRICE
FROM MANUALS
WHERE MANUAL_PRICE > 500;

SELECT PUBLISHED_YEAR
FROM MANUALS
WHERE PUBLISHED_YEAR > 2022;

-- ORDER BY CLAUSE
SELECT STUDENT_NAME, AGE
FROM STUDENT
ORDER BY AGE;

SELECT STUDENT_NAME, AGE
FROM STUDENT
ORDER BY AGE ASC;

SELECT STUDENT_NAME, AGE
FROM STUDENT
ORDER BY AGE DESC;

SELECT STUDENT_NAME, AGE
FROM STUDENT
ORDER BY AGE
LIMIT 3;

SELECT MANUAL_NAME
FROM MANUALS
LIMIT 3;

SELECT MANUAL_NAME, PUBLISHED_YEAR 
FROM MANUALS
ORDER BY PUBLISHED_YEAR 
LIMIT 5;


SELECT DEPARTMENT_ID, DEPT_NAME
FROM DEPARTMENT
ORDER BY DEPT_NAME;

SELECT DEPARTMENT_ID, DEPT_NAME
FROM DEPARTMENT
ORDER BY DEPT_NAME
LIMIT 5;


-- USING AND OPERATOR
SELECT * FROM Student
WHERE Age > 20 AND Gender = 'M';

-- OR OPERATOR
SELECT * FROM Student
WHERE Age > 20 OR Gender = 'M';

-- LIKE OPERATOR
SELECT* FROM DEPARTMENT
WHERE DEPT_NAME LIKE '%A%';

--  BETWEEN OPERATOR
SELECT STUDENT_NAME AS NAMES, AGE
FROM STUDENT
WHERE AGE BETWEEN 21 AND 25;



